MONGO_SERVER_URL: localhost
MONGO_SERVER_PORT: 28017
MONGO_USERNAME: root
MONGO_PASSWORD: root1

USER_PROFILES_JWT_PRIVATE_KEY: src/main/resources/app-local.key
USER_PROFILES_JWT_PUBLIC_KEY: src/main/resources/app-local.pub
JWT_ISSUER: library.productdock.rs

LOG_TO_FILE: false