spring:
  data:
    mongodb:
      authentication-database: user-profiles
      host: ${mongo.server.url:localhost}
      port: ${mongo.server.port:28017}
      username: ${mongo.username:root}
      password: ${mongo.password:root1}
      database: user-profiles

security:
  jwt:
    private.key: classpath:app.key
    public.key: classpath:app.pub
    jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs

server:
  port: 8085