name: Build and upload to container registry

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

jobs:
  build-upload-prod:
    uses: ProductDock/rbc-github-workflows/.github/workflows/build-registry-upload.yml@main
    secrets: inherit